### ISSUE TITLE
Please remove Pale Moon branding

### ISSUE THREAD

**Issue by wolfbeast** [dbsoft/White-Star-Old#1]
Please remove Pale Moon branding assets from all branches in your tree.

https://github.com/dbsoft/White-Star/tree/{branch}/palemoon/branding
directories beta/ official/ and unstable/

**Comment by dbsoft** [comment]
Not sure if I am required to, since they are not used and part of the code forked from you... but in the hope of fostering a better relationship with you in the future... they will be removed by the next monthly release if not sooner.

**Comment by wolfbeast** [comment]
I appreciate your cooperation.
As for whether you are required to... yes you are, when I request it. You're not building Pale Moon, this repo is not for Pale Moon, and you're not using the assets (or allowed to use them anyway), and the branding is proprietary so I am asking that you don't include it in your source distribution from this point forward. Pretty straight-forward, I think.

**Comment by dbsoft** [comment]
Well, not going to argue about it, but I think whether it is required legally is questionable, but I will be removing it so it does not matter either way.

**Comment by dbsoft** [comment]
@wolfbeast If you aren't going to be using UXP as a product anymore, can I rename my MXP back to UXP for all platforms?

**Comment by wolfbeast** [comment]
I'll get back to you on that. Please hold off on using UXP for the time being to avoid confusion.

**Comment by dbsoft** [comment]
@wolfbeast Sure thing, just thinking about reorganizing things.... since you don't have a public repository anymore and I am doing the changes by hand now... don't need separate branches and such. So instead of removing the branding from all the branches, I might just merger the Mac branch to master, and delete all the existing branches.  Then I can link to my fork of UXP and basically replicate what you had been doing before you went private.

**Comment by wolfbeast** [comment]
I honestly don't care how you organize it internally; I'm just asking you to no longer publish the branding materials as part of your effort/repo.

**Comment by dbsoft** [comment]
Just explaining why I am asking about the MXP/UXP thing.... it is part of my reorganization plan I am developing.

**Comment by dbsoft** [comment]
Has a decision been made regarding UXP? Or is the "hold off" an indefinite thing?

**Comment by wolfbeast** [comment]
How about you first remove the branding materials that I opened this issue for? I'd prefer not to DMCA you.

It's unlikely we'll ever "un-archive" UXP at this point, so if claiming the name of it is such a big deal to you then I won't stop you.

**Comment by dbsoft** [comment]
I have published a new White Star repository with the referenced materials removed.  I am leaving this archived repository visible for about a month for people to get whatever history they need from it before setting it private, and at some point deletion. If there is any problem with that let me know, but I am closing this issue now.
